services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: TaskListDb
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build: .
    container_name: dotnetapp
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo
      - MongoDbSettings__DatabaseName=TaskListDb
    ports: 
      - 8080:8080

volumes:
  mongo-data:
